export { MasterPageModule } from './master-page/MasterPageModule';
export { HomeModule } from './home/HomeModule';
export { HeaderModule } from './header/HeaderModule';
export { FooterModule } from './footer/FooterModule';
export { ContainerModule } from './container/ContainerModule';
export { EventsModule } from './events/EventsModule';
export { TestRouteModule } from './test-route/TestRouteModule';
export { AuthModule } from './auth/AuthModule';
export { BetOptionsModule } from './bet-options/BetOptionsModule';
export { AdminModule } from './admin/AdminModule';
// export { TestRouteModule } from './test-route/TestRouteModule';
